name: todo
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_staggered_grid_view: ^0.6.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: "launcher_icon"
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
